site:
  title: Spring Session
  start_page: java-project::index.adoc
content:
  sources:
    - url: ./
      branches: HEAD
    - url: ../antora-java-examples
      branches: HEAD
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
pipeline:
  extensions:
    - require: ./antora/extensions/include.js
      content-catalog:
        samples:
          module: 'ROOT'
          family: 'example'
          url:
            includes:
              - '.*examples'
        readme:
          module: 'ROOT'
          family: 'page'
          path:
            includes:
              - '.*README.adoc'